services:
  - type: web
    name: devops-project-313
    runtime: docker
    plan: free
    branch: main
    autoDeploy: true

    envVars:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false
      - key: SENTRY_DSN
        sync: false